### ISSUE TITLE
Is it possible to use this with my own psql connection?

### ISSUE THREAD

**Issue by bbigras** [quietboil/include-postgres-sql#1]
I'm already using another library for the psql pool.

Can I only generate the SQL string (a bit like the old [include-sql-helper](https://crates.io/crates/include-sql-helper) allowed)?

**Comment by quietboil** [comment]
Out of the box? No.

However, note that even *out of the box* this crate was intended to be used as an example/prototype/inspiration for your own implementation. The simple fact is this - current implementation reflects my biases on database access. Some might (and likely do) disagree with those.

The simplest way to handle your situation, IMHO, is to take this crate and adopt it for your specific needs - clone it into your own crate and change `impl_sql` to implement the generated trait for the structs that you need instead of the default `postgres::Client` and (maybe) `postgres::Transaction` (depends on how that other library handles transactions). That's really all there is to it.

However, if you do not with to use the generated methods, you can take this one step (or two, or three 😄) further - remove bits that you do not want and make your `impl_sql` generate maybe `const` for static SQL - those without IN - you can use `sql_literal` macro as-is and forgo everything else that the crate provides. That macro is not documented because it was intended to be an internal helper. However, you can see how it is used in the crate.

Dynamic - those that have parameterized IN - are more involved. You probably would want to make your `impl_sql` generate a function/method that build and returns that SQL. You can find one approach (and helper macros it uses) to handle that in the implementation. Look for how `dynamic_sql` macro is used.
